import React from 'react';

const About = () => {
  return (
    <div className="bg-white text-gray-800 p-8 rounded-lg mt-10">
      <h2 className="text-3xl font-semibold text-pink-600 mb-4">About Autofill AI</h2>
      <p className="text-lg mb-4">
        Autofill AI is an innovative software designed to assist students in their educational journey. With a commitment to promoting academic integrity, our software is intended to supplement your studies and provide a reliable tool for enhancing your understanding of course materials.
      </p>
      <p className="text-lg mb-4">
        At Autofill AI, we prioritize responsible and ethical use of our software. It is crucial that users employ Autofill AI as an aid in their learning process, fostering knowledge acquisition and comprehension. We strongly discourage any form of academic misconduct, cheating, or unethical behavior.
      </p>
      <p className="text-lg mb-4">
        Our mission is to provide students with a valuable educational resource that supports their academic endeavors and ensures compliance with the highest standards of academic integrity. We encourage users to verify and cross-reference any content generated by Autofill AI, as AI-generated content may have occasional inaccuracies.
      </p>
      <p className="text-lg">
        Thank you for choosing Autofill AI as your educational companion. Your responsible and ethical use of our software is essential to maintain its integrity and purpose.
      </p>
    </div>
  );
};

export default About;
