import React from "react";

function AutoFillTerms() {
  return (
    <div className="bg-white p-8 rounded-lg shadow-md mt-10">
      <h1 className="text-3xl text-pink-500 mb-6 font-bold">
        Autofill AI: Comprehensive Terms and Conditions
      </h1>

      <div className="text-gray-700">
        <p className="mb-4">
          These Terms and Conditions ("Terms") are a legally binding agreement
          between you, the user, and Autofill AI, a software application
          provided for educational and proof-of-concept purposes. By accessing
          and utilizing this software, you indicate your unequivocal consent to
          be bound by these Terms. Therefore, please take the time to peruse
          this document meticulously.
        </p>

        <h2 className="text-xl text-pink-500 mb-4 font-semibold">
          1. Educational and Ethical Use
        </h2>
        <p className="mb-4">
          1.1. Autofill AI is expressly intended to serve as an educational and
          proof-of-concept tool, crafted to facilitate the comprehension, study,
          and revision of academic course materials. Its purpose is to enhance
          the learning experience, foster academic growth, and promote
          responsible knowledge acquisition.
        </p>
        <p className="mb-4">
          1.2. By engaging with this software, you affirm your commitment to use
          it solely for educational purposes as defined herein. Any attempt to
          employ the software in contravention of its intended educational
          purpose is strictly prohibited. Such misuse includes, but is not
          limited to, utilizing the software for cheating, academic misconduct,
          or plagiarism.
        </p>

        <h2 className="text-xl text-pink-500 mb-4 font-semibold">
          2. Unlawful Activities
        </h2>
        <p className="mb-4">
          2.1. The developer of Autofill AI unequivocally condemns the use of
          the software for purposes that transgress applicable laws,
          regulations, or ethical standards. The use of this software for
          cheating, academic misconduct, plagiarism, copyright infringement, or
          any other activity deemed unlawful or unethical is prohibited.
        </p>
        <p className="mb-4">
          2.2. Users of Autofill AI are solely responsible for their actions
          while using the software. In no event shall the developer be held
          liable for any actions or omissions that violate these Terms, academic
          integrity, or applicable laws.
        </p>

        <h2 className="text-xl text-pink-500 mb-4 font-semibold">
          3. Developer's Non-Responsibility
        </h2>
        <p className="mb-4">
          3.1. The developer of Autofill AI shall not, under any circumstances,
          be held accountable for any academic dishonesty, misconduct, or legal
          violations committed by users of this software. Users assume full and
          exclusive responsibility for their actions.
        </p>

        <h2 className="text-xl text-pink-500 mb-4 font-semibold">
          4. Acceptance of Terms
        </h2>
        <p className="mb-4">
          4.1. Your use of Autofill AI signifies your explicit acceptance of
          these Terms. Should you disagree with any aspect of these Terms or
          find them in any way unacceptable, your only recourse is to abstain
          from using the software.
        </p>

        <h2 className="text-xl text-pink-500 mb-4 font-semibold">
          5. Original Work Submission
        </h2>
        <p className="mb-4">
          5.1. When utilizing Autofill AI, users are obligated to submit
          exclusively their own original work. While the software can assist in
          content generation, it is incumbent upon the user to ensure the
          accuracy, authenticity, and originality of the content produced.
        </p>
        <p className="mb-4">
          5.2. It is essential to recognize that AI-generated content may, at
          times, exhibit inaccuracies, inconsistencies, or errors. Therefore,
          users should exercise due diligence and employ critical judgment when
          relying on content generated by Autofill AI. Cross-referencing and
          verification of AI-generated content is strongly advised.
        </p>

        <h2 className="text-xl text-pink-500 mb-4 font-semibold">
          6. Risk Acknowledgment
        </h2>
        <p className="mb-4">
          6.1. Users acknowledge and understand that there are inherent risks
          associated with relying on AI-generated content. The developer makes
          no warranties, representations, or guarantees concerning the accuracy,
          completeness, or quality of the content output by the software.
        </p>
        <p className="mb-4">
          6.2. Consequently, users are encouraged to exercise due caution and
          undertake verification procedures when relying on AI-generated content
          to mitigate potential risks associated with inaccuracies or errors.
        </p>

        <h2 className="text-xl text-pink-500 mb-4 font-semibold">
          7. Liability Waiver
        </h2>
        <p className="mb-4">
          7.1. Users expressly agree not to hold the developer liable for any
          adverse academic, legal, or other consequences that may ensue from
          improper use of Autofill AI. The developer is indemnified and held
          harmless from and against any and all liabilities arising from the
          user's actions and conduct.
        </p>

        <h2 className="text-xl text-pink-500 mb-4 font-semibold">
          8. Responsible and Ethical Use
        </h2>
        <p className="mb-4">
          8.1. It is imperative that users employ Autofill AI in an ethical and
          lawful manner. The software is expressly designed as an educational
          tool to complement and enhance the educational experience. It is not
          intended to be employed as a means to circumvent academic regulations,
          undermine academic integrity, or engage in unethical behavior.
        </p>
        <p className="mb-4">
          8.2. Users are encouraged to utilize Autofill AI responsibly and
          ethically, ensuring that their engagement with the software upholds
          the highest standards of academic integrity and complies with the
          prevailing laws and ethical principles governing their educational
          institution.
        </p>

        <h2 className="text-xl text-pink-500 mb-4 font-semibold">
          9. Modifications to Terms
        </h2>
        <p className="mb-4">
          9.1. The developer reserves the right to amend, update, or revise
          these Terms at any time, without prior notice. Users are encouraged to
          periodically review these Terms to remain apprised of any changes or
          updates. Continued use of the software following any modification to
          these Terms constitutes acceptance of the revised Terms.
        </p>

        <h2 className="text-xl text-pink-500 mb-4 font-semibold">
          10. Conclusion
        </h2>
        <p className="mb-4">
          In conclusion, the utilization of Autofill AI is predicated upon the
          foundation of responsible and ethical use, primarily for educational
          and knowledge enrichment purposes. Users are urged to exercise
          prudence, ethical discernment, and sound judgment when engaging with
          this software, as a commitment to academic integrity and the adherence
          to applicable laws are paramount.
        </p>
        <p>
          By continuing to use Autofill AI, you manifest your assent to these
          comprehensive Terms and Conditions, underscoring your commitment to
          responsible and ethical engagement with the software. Should you have
          any concerns, questions, or require clarification on any aspect of
          these Terms, please do not hesitate to contact us for further
          information.
        </p>
      </div>
    </div>
  );
}

export default AutoFillTerms;
